entrypoint: normalize 2-space indent

diff --git a/images/base/files/usr/local/bin/entrypoint b/images/base/files/usr/local/bin/entrypoint
--- a/images/base/files/usr/local/bin/entrypoint
+++ b/images/base/files/usr/local/bin/entrypoint
@@ -465,23 +465,23 @@ enable_network_magic(){
   curr_ipv4="$( (head -n1 <(timeout 5 getent ahostsv4 "$(hostname)") | cut -d' ' -f1) || true)"
   echo "INFO: Detected IPv4 address: ${curr_ipv4}" >&2
   if [ -f /kind/old-ipv4 ]; then
-      old_ipv4=$(cat /kind/old-ipv4)
-      echo "INFO: Detected old IPv4 address: ${old_ipv4}" >&2
-      # sanity check that we have a current address
-      if [[ -z $curr_ipv4 ]]; then
-        echo "ERROR: Have an old IPv4 address but no current IPv4 address (!)" >&2
-        exit 1
-      fi
-      if [[ "${old_ipv4}" != "${curr_ipv4}" ]]; then
-        should_fix_certificate=true
-        sed_ipv4_command="s#\b$(regex_escape_ip "${old_ipv4}")\b#${curr_ipv4}#g"
-        for f in "${files_to_update[@]}"; do
-          # kubernetes manifests are only present on control-plane nodes
-          if [[ -f "$f" ]]; then
-            sed -i "${sed_ipv4_command}" "$f"
-          fi
-        done
-      fi
+    old_ipv4=$(cat /kind/old-ipv4)
+    echo "INFO: Detected old IPv4 address: ${old_ipv4}" >&2
+    # sanity check that we have a current address
+    if [[ -z $curr_ipv4 ]]; then
+      echo "ERROR: Have an old IPv4 address but no current IPv4 address (!)" >&2
+      exit 1
+    fi
+    if [[ "${old_ipv4}" != "${curr_ipv4}" ]]; then
+      should_fix_certificate=true
+      sed_ipv4_command="s#\b$(regex_escape_ip "${old_ipv4}")\b#${curr_ipv4}#g"
+      for f in "${files_to_update[@]}"; do
+        # kubernetes manifests are only present on control-plane nodes
+        if [[ -f "$f" ]]; then
+          sed -i "${sed_ipv4_command}" "$f"
+        fi
+      done
+    fi
   fi
   if [[ -n $curr_ipv4 ]]; then
     echo -n "${curr_ipv4}" >/kind/old-ipv4
@@ -491,22 +491,22 @@ enable_network_magic(){
   curr_ipv6="$( (head -n1 <(timeout 5 getent ahostsv6 "$(hostname)") | cut -d' ' -f1) || true)"
   echo "INFO: Detected IPv6 address: ${curr_ipv6}" >&2
   if [ -f /kind/old-ipv6 ]; then
-      old_ipv6=$(cat /kind/old-ipv6)
-      echo "INFO: Detected old IPv6 address: ${old_ipv6}" >&2
-      # sanity check that we have a current address
-      if [[ -z $curr_ipv6 ]]; then
-        echo "ERROR: Have an old IPv6 address but no current IPv6 address (!)" >&2
-      fi
-      if [[ "${old_ipv6}" != "${curr_ipv6}" ]]; then
-        should_fix_certificate=true
-        sed_ipv6_command="s#\b$(regex_escape_ip "${old_ipv6}")\b#${curr_ipv6}#g"
-        for f in "${files_to_update[@]}"; do
-          # kubernetes manifests are only present on control-plane nodes
-          if [[ -f "$f" ]]; then
-            sed -i "${sed_ipv6_command}" "$f"
-          fi
-        done
-      fi
+    old_ipv6=$(cat /kind/old-ipv6)
+    echo "INFO: Detected old IPv6 address: ${old_ipv6}" >&2
+    # sanity check that we have a current address
+    if [[ -z $curr_ipv6 ]]; then
+      echo "ERROR: Have an old IPv6 address but no current IPv6 address (!)" >&2
+    fi
+    if [[ "${old_ipv6}" != "${curr_ipv6}" ]]; then
+      should_fix_certificate=true
+      sed_ipv6_command="s#\b$(regex_escape_ip "${old_ipv6}")\b#${curr_ipv6}#g"
+      for f in "${files_to_update[@]}"; do
+        # kubernetes manifests are only present on control-plane nodes
+        if [[ -f "$f" ]]; then
+          sed -i "${sed_ipv6_command}" "$f"
+        fi
+      done
+    fi
   fi
   if [[ -n $curr_ipv6 ]]; then
     echo -n "${curr_ipv6}" >/kind/old-ipv6
